### ISSUE TITLE
UnicodeDecodeError on workspace event

### ISSUE THREAD

**Issue by willemw12** [ziberna/i3-py#9]
When running a simple python3 test, using:
def my_function(event, data, subscription):
...
subscription = i3.Subscription(my_function, 'workspace')

Then the event thread crashes when visiting (mod-<1..0>) certain invisible workspaces. Not all invisible workspaces cause a crash:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.3/threading.py", line 637, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.3/site-packages/i3.py", line 324, in run
    self.listen()
  File "/usr/lib/python3.3/site-packages/i3.py", line 338, in listen
    event = self.event_socket.receive()
  File "/usr/lib/python3.3/site-packages/i3.py", line 218, in receive
    return self.unpack(data)
  File "/usr/lib/python3.3/site-packages/i3.py", line 248, in unpack
    payload = data[self.struct_header_size:msg_size].decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 992: invalid start byte

**Comment by mossblaser** [comment]
Hello,

I have fixed this bug in [my fork](https://github.com/mossblaser/i3-py) and have submitted a [pull request](https://github.com/ziberna/i3-py/pull/10).

I hope this scratches your itch as much as mine!

Jonathan
